marketplace_homepage:
    path:     /
    defaults: { _controller: MarketplaceBundle:Marketplace:listLoans }

list_loans:
    path:     /loans
    defaults: { _controller: MarketplaceBundle:Marketplace:listLoans }
